insta_settings:
    driver_path_win : "./chrome/chromedriver_win.exe"  # chorme path for windows
    driver_path_mac : "./chrome/chromedriver_mac"  # chorme path for mac
    driver_path_lin : "./chrome/chromedriver_linux"  # chorme path for linux
    driver_no_sandbox: False  # set it True for not GUI user
    driver_headless: False  # set it True if you want no Chrome window

    # login: True  # force to login right now
    insta_id: ""  # must login
    insta_pw: ""  # must login

    thres_links: 12  # threshold for spidering the links

db_settings:
    db_name: "example.db"  # database name
    table_name: "exam"  # table

spider_settings:
    insert_freq: 5  # insert every n batch data
    output_path: "./output"  # extract the image and data path
    img_fmt: ".jpg"  # output image format

    recreate: False  # whether to force recreate database table at the first time
    stage: 0  # 0: run all / 1: run only `get_links` / 2: run only `get_data`, from exists links file 
